spring:
  application:
    - name: spotme-api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-svc-route
          uri: ${AUTH_SVC_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth**
          filters:
            - RewritePath=/auth(?<segment>.*), /api/v1/auth$\{segment}
            - AddResponseHeader=X-Powered-By,SpotMe Gateway Service

        - id: user-svc-route
          uri: ${USER_SVC_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RewritePath=/info(?<segment>.*), /api/v1/info$\{segment}
            - AddResponseHeader=X-Powered-By,SpotMe Gateway Service

        - id: match-svc-route
          uri: ${MATCH_SVC_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/match/**
          filters:
            - RewritePath=/info(?<segment>.*), /api/v1/info$\{segment}
            - AddResponseHeader=X-Powered-By,SpotMe Gateway Service

        - id: gym-svc-route
          uri: ${GYM_SVC_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/gym/**
          filters:
            - RewritePath=/info(?<segment>.*), /api/v1/info$\{segment}
            - AddResponseHeader=X-Powered-By,SpotMe Gateway Service

        - id: friends-svc-route
          uri: ${FRIENDS_SVC_URL:http://localhost:8085}
          predicates:
            - Path=/api/v1/friends/**
          filters:
            - RewritePath=/info(?<segment>.*), /api/v1/info$\{segment}
            - AddResponseHeader=X-Powered-By,SpotMe Gateway Service

        - id: posts-route
          uri: ${POSTS_ROUTE_URI:http://localhost:8086}
          predicates:
            - Path=/posts/**
          filters:
            - RewritePath=/info(?<segment>.*), /api/v1/info$\{segment}
            - AddResponseHeader=X-Powered-By,SpotMe Gateway Service

        - id: google-route
          uri: http://localhost:8080
          predicates:
            - Path=/swagger-ui/index.html#/**
          filters:
            - RewritePath=/info(?<segment>.*), /api/v1/info$\{segment}
            - AddResponseHeader=X-Powered-By,SpotMe Gateway Service

        - id: info-route
          uri: http://localhost:8080
          predicates:
            - Path=/info**
          filters:
            - RewritePath=/info(?<segment>.*), /api/v1/info$\{segment} #/api/v1/movies/$\{segment}

        - id: swagger-route
          uri: http://localhost:8080
          predicates:
            - Path=/swagger**
          filters:
            - RewritePath=^/swagger(?<segment>.*),/swagger-ui/index.html#/$\{segment} #/api/v1/movies/$\{segment}
server:
  port: 8100

